-- Seed all 168 Grind 75 problems (points = minutes * difficulty multiplier).
-- Generated from the repo-root `problems` file.

INSERT INTO problems (slug, title, difficulty, minutes, points, order_index) VALUES
  ('two-sum', 'Two Sum', 'Easy', 15, 15, 1),
  ('valid-parentheses', 'Valid Parentheses', 'Easy', 20, 20, 2),
  ('merge-two-sorted-lists', 'Merge Two Sorted Lists', 'Easy', 20, 20, 3),
  ('best-time-to-buy-and-sell-stock', 'Best Time to Buy and Sell Stock', 'Easy', 20, 20, 4),
  ('valid-palindrome', 'Valid Palindrome', 'Easy', 15, 15, 5),
  ('invert-binary-tree', 'Invert Binary Tree', 'Easy', 15, 15, 6),
  ('valid-anagram', 'Valid Anagram', 'Easy', 15, 15, 7),
  ('binary-search', 'Binary Search', 'Easy', 15, 15, 8),
  ('flood-fill', 'Flood Fill', 'Easy', 20, 20, 9),
  ('lowest-common-ancestor-of-a-binary-search-tree', 'Lowest Common Ancestor of a Binary Search Tree', 'Easy', 20, 20, 10),
  ('balanced-binary-tree', 'Balanced Binary Tree', 'Easy', 15, 15, 11),
  ('linked-list-cycle', 'Linked List Cycle', 'Easy', 20, 20, 12),
  ('implement-queue-using-stacks', 'Implement Queue using Stacks', 'Easy', 20, 20, 13),
  ('first-bad-version', 'First Bad Version', 'Easy', 20, 20, 14),
  ('ransom-note', 'Ransom Note', 'Easy', 15, 15, 15),
  ('climbing-stairs', 'Climbing Stairs', 'Easy', 20, 20, 16),
  ('longest-palindrome', 'Longest Palindrome', 'Easy', 20, 20, 17),
  ('reverse-linked-list', 'Reverse Linked List', 'Easy', 20, 20, 18),
  ('majority-element', 'Majority Element', 'Easy', 20, 20, 19),
  ('add-binary', 'Add Binary', 'Easy', 15, 15, 20),
  ('diameter-of-binary-tree', 'Diameter of Binary Tree', 'Easy', 30, 30, 21),
  ('middle-of-the-linked-list', 'Middle of the Linked List', 'Easy', 20, 20, 22),
  ('maximum-depth-of-binary-tree', 'Maximum Depth of Binary Tree', 'Easy', 15, 15, 23),
  ('contains-duplicate', 'Contains Duplicate', 'Easy', 15, 15, 24),
  ('meeting-rooms', 'Meeting Rooms', 'Easy', 20, 20, 25),
  ('roman-to-integer', 'Roman to Integer', 'Easy', 20, 20, 26),
  ('backspace-string-compare', 'Backspace String Compare', 'Easy', 15, 15, 27),
  ('counting-bits', 'Counting Bits', 'Easy', 15, 15, 28),
  ('same-tree', 'Same Tree', 'Easy', 20, 20, 29),
  ('number-of-1-bits', 'Number of 1 Bits', 'Easy', 15, 15, 30),
  ('longest-common-prefix', 'Longest Common Prefix', 'Easy', 20, 20, 31),
  ('single-number', 'Single Number', 'Easy', 15, 15, 32),
  ('palindrome-linked-list', 'Palindrome Linked List', 'Easy', 20, 20, 33),
  ('move-zeroes', 'Move Zeroes', 'Easy', 20, 20, 34),
  ('symmetric-tree', 'Symmetric Tree', 'Easy', 20, 20, 35),
  ('missing-number', 'Missing Number', 'Easy', 15, 15, 36),
  ('palindrome-number', 'Palindrome Number', 'Easy', 15, 15, 37),
  ('convert-sorted-array-to-binary-search-tree', 'Convert Sorted Array to Binary Search Tree', 'Easy', 20, 20, 38),
  ('reverse-bits', 'Reverse Bits', 'Easy', 15, 15, 39),
  ('subtree-of-another-tree', 'Subtree of Another Tree', 'Easy', 20, 20, 40),
  ('squares-of-a-sorted-array', 'Squares of a Sorted Array', 'Easy', 20, 20, 41),
  ('maximum-subarray', 'Maximum Subarray', 'Medium', 20, 40, 42),
  ('insert-interval', 'Insert Interval', 'Medium', 25, 50, 43),
  ('01-matrix', '01 Matrix', 'Medium', 30, 60, 44),
  ('k-closest-points-to-origin', 'K Closest Points to Origin', 'Medium', 30, 60, 45),
  ('longest-substring-without-repeating-characters', 'Longest Substring Without Repeating Characters', 'Medium', 30, 60, 46),
  ('3sum', '3Sum', 'Medium', 30, 60, 47),
  ('binary-tree-level-order-traversal', 'Binary Tree Level Order Traversal', 'Medium', 20, 40, 48),
  ('clone-graph', 'Clone Graph', 'Medium', 25, 50, 49),
  ('evaluate-reverse-polish-notation', 'Evaluate Reverse Polish Notation', 'Medium', 30, 60, 50),
  ('course-schedule', 'Course Schedule', 'Medium', 30, 60, 51),
  ('implement-trie-prefix-tree', 'Implement Trie (Prefix Tree)', 'Medium', 35, 70, 52),
  ('coin-change', 'Coin Change', 'Medium', 25, 50, 53),
  ('product-of-array-except-self', 'Product of Array Except Self', 'Medium', 30, 60, 54),
  ('min-stack', 'Min Stack', 'Medium', 20, 40, 55),
  ('validate-binary-search-tree', 'Validate Binary Search Tree', 'Medium', 20, 40, 56),
  ('number-of-islands', 'Number of Islands', 'Medium', 25, 50, 57),
  ('rotting-oranges', 'Rotting Oranges', 'Medium', 30, 60, 58),
  ('search-in-rotated-sorted-array', 'Search in Rotated Sorted Array', 'Medium', 30, 60, 59),
  ('combination-sum', 'Combination Sum', 'Medium', 30, 60, 60),
  ('permutations', 'Permutations', 'Medium', 30, 60, 61),
  ('merge-intervals', 'Merge Intervals', 'Medium', 30, 60, 62),
  ('lowest-common-ancestor-of-a-binary-tree', 'Lowest Common Ancestor of a Binary Tree', 'Medium', 25, 50, 63),
  ('time-based-key-value-store', 'Time Based Key-Value Store', 'Medium', 35, 70, 64),
  ('accounts-merge', 'Accounts Merge', 'Medium', 30, 60, 65),
  ('sort-colors', 'Sort Colors', 'Medium', 25, 50, 66),
  ('word-break', 'Word Break', 'Medium', 30, 60, 67),
  ('partition-equal-subset-sum', 'Partition Equal Subset Sum', 'Medium', 30, 60, 68),
  ('string-to-integer-atoi', 'String to Integer (atoi)', 'Medium', 25, 50, 69),
  ('spiral-matrix', 'Spiral Matrix', 'Medium', 25, 50, 70),
  ('subsets', 'Subsets', 'Medium', 30, 60, 71),
  ('binary-tree-right-side-view', 'Binary Tree Right Side View', 'Medium', 20, 40, 72),
  ('longest-palindromic-substring', 'Longest Palindromic Substring', 'Medium', 25, 50, 73),
  ('unique-paths', 'Unique Paths', 'Medium', 20, 40, 74),
  ('construct-binary-tree-from-preorder-and-inorder-traversal', 'Construct Binary Tree from Preorder and Inorder Traversal', 'Medium', 25, 50, 75),
  ('container-with-most-water', 'Container With Most Water', 'Medium', 35, 70, 76),
  ('letter-combinations-of-a-phone-number', 'Letter Combinations of a Phone Number', 'Medium', 30, 60, 77),
  ('word-search', 'Word Search', 'Medium', 30, 60, 78),
  ('find-all-anagrams-in-a-string', 'Find All Anagrams in a String', 'Medium', 30, 60, 79),
  ('minimum-height-trees', 'Minimum Height Trees', 'Medium', 30, 60, 80),
  ('task-scheduler', 'Task Scheduler', 'Medium', 35, 70, 81),
  ('lru-cache', 'LRU Cache', 'Medium', 30, 60, 82),
  ('kth-smallest-element-in-a-bst', 'Kth Smallest Element in a BST', 'Medium', 25, 50, 83),
  ('daily-temperatures', 'Daily Temperatures', 'Medium', 30, 60, 84),
  ('house-robber', 'House Robber', 'Medium', 25, 50, 85),
  ('gas-station', 'Gas Station', 'Medium', 30, 60, 86),
  ('next-permutation', 'Next Permutation', 'Medium', 30, 60, 87),
  ('valid-sudoku', 'Valid Sudoku', 'Medium', 35, 70, 88),
  ('group-anagrams', 'Group Anagrams', 'Medium', 25, 50, 89),
  ('maximum-product-subarray', 'Maximum Product Subarray', 'Medium', 30, 60, 90),
  ('design-add-and-search-words-data-structure', 'Design Add and Search Words Data Structure', 'Medium', 35, 70, 91),
  ('pacific-atlantic-water-flow', 'Pacific Atlantic Water Flow', 'Medium', 30, 60, 92),
  ('remove-nth-node-from-end-of-list', 'Remove Nth Node From End of List', 'Medium', 20, 40, 93),
  ('shortest-path-to-get-food', 'Shortest Path to Get Food', 'Medium', 30, 60, 94),
  ('find-the-duplicate-number', 'Find the Duplicate Number', 'Medium', 20, 40, 95),
  ('top-k-frequent-words', 'Top K Frequent Words', 'Medium', 30, 60, 96),
  ('longest-increasing-subsequence', 'Longest Increasing Subsequence', 'Medium', 30, 60, 97),
  ('graph-valid-tree', 'Graph Valid Tree', 'Medium', 30, 60, 98),
  ('course-schedule-ii', 'Course Schedule II', 'Medium', 35, 70, 99),
  ('swap-nodes-in-pairs', 'Swap Nodes in Pairs', 'Medium', 25, 50, 100),
  ('path-sum-ii', 'Path Sum II', 'Medium', 25, 50, 101),
  ('longest-consecutive-sequence', 'Longest Consecutive Sequence', 'Medium', 30, 60, 102),
  ('rotate-array', 'Rotate Array', 'Medium', 25, 50, 103),
  ('odd-even-linked-list', 'Odd Even Linked List', 'Medium', 25, 50, 104),
  ('decode-string', 'Decode String', 'Medium', 30, 60, 105),
  ('contiguous-array', 'Contiguous Array', 'Medium', 30, 60, 106),
  ('maximum-width-of-binary-tree', 'Maximum Width of Binary Tree', 'Medium', 20, 40, 107),
  ('find-k-closest-elements', 'Find K Closest Elements', 'Medium', 30, 60, 108),
  ('longest-repeating-character-replacement', 'Longest Repeating Character Replacement', 'Medium', 30, 60, 109),
  ('inorder-successor-in-bst', 'Inorder Successor in BST', 'Medium', 30, 60, 110),
  ('jump-game', 'Jump Game', 'Medium', 20, 40, 111),
  ('add-two-numbers', 'Add Two Numbers', 'Medium', 25, 50, 112),
  ('generate-parentheses', 'Generate Parentheses', 'Medium', 25, 50, 113),
  ('sort-list', 'Sort List', 'Medium', 25, 50, 114),
  ('number-of-connected-components-in-an-undirected-graph', 'Number of Connected Components in an Undirected Graph', 'Medium', 30, 60, 115),
  ('minimum-knight-moves', 'Minimum Knight Moves', 'Medium', 35, 70, 116),
  ('subarray-sum-equals-k', 'Subarray Sum Equals K', 'Medium', 35, 70, 117),
  ('asteroid-collision', 'Asteroid Collision', 'Medium', 30, 60, 118),
  ('random-pick-with-weight', 'Random Pick with Weight', 'Medium', 25, 50, 119),
  ('kth-largest-element-in-an-array', 'Kth Largest Element in an Array', 'Medium', 30, 60, 120),
  ('maximal-square', 'Maximal Square', 'Medium', 30, 60, 121),
  ('rotate-image', 'Rotate Image', 'Medium', 25, 50, 122),
  ('binary-tree-zigzag-level-order-traversal', 'Binary Tree Zigzag Level Order Traversal', 'Medium', 25, 50, 123),
  ('design-hit-counter', 'Design Hit Counter', 'Medium', 30, 60, 124),
  ('path-sum-iii', 'Path Sum III', 'Medium', 35, 70, 125),
  ('pow-x-n', 'Pow(x, n)', 'Medium', 20, 40, 126),
  ('search-a-2d-matrix', 'Search a 2D Matrix', 'Medium', 30, 60, 127),
  ('largest-number', 'Largest Number', 'Medium', 20, 40, 128),
  ('decode-ways', 'Decode Ways', 'Medium', 25, 50, 129),
  ('meeting-rooms-ii', 'Meeting Rooms II', 'Medium', 30, 60, 130),
  ('reverse-integer', 'Reverse Integer', 'Medium', 25, 50, 131),
  ('set-matrix-zeroes', 'Set Matrix Zeroes', 'Medium', 25, 50, 132),
  ('reorder-list', 'Reorder List', 'Medium', 25, 50, 133),
  ('encode-and-decode-strings', 'Encode and Decode Strings', 'Medium', 25, 50, 134),
  ('cheapest-flights-within-k-stops', 'Cheapest Flights Within K Stops', 'Medium', 45, 90, 135),
  ('all-nodes-distance-k-in-binary-tree', 'All Nodes Distance K in Binary Tree', 'Medium', 25, 50, 136),
  ('3sum-closest', '3Sum Closest', 'Medium', 30, 60, 137),
  ('rotate-list', 'Rotate List', 'Medium', 25, 50, 138),
  ('find-minimum-in-rotated-sorted-array', 'Find Minimum in Rotated Sorted Array', 'Medium', 30, 60, 139),
  ('basic-calculator-ii', 'Basic Calculator II', 'Medium', 30, 60, 140),
  ('combination-sum-iv', 'Combination Sum IV', 'Medium', 35, 70, 141),
  ('insert-delete-getrandom-o-1', 'Insert Delete GetRandom O(1)', 'Medium', 20, 40, 142),
  ('non-overlapping-intervals', 'Non-overlapping Intervals', 'Medium', 20, 40, 143),
  ('minimum-window-substring', 'Minimum Window Substring', 'Hard', 30, 90, 144),
  ('serialize-and-deserialize-binary-tree', 'Serialize and Deserialize Binary Tree', 'Hard', 40, 120, 145),
  ('trapping-rain-water', 'Trapping Rain Water', 'Hard', 35, 105, 146),
  ('find-median-from-data-stream', 'Find Median from Data Stream', 'Hard', 30, 90, 147),
  ('word-ladder', 'Word Ladder', 'Hard', 45, 135, 148),
  ('basic-calculator', 'Basic Calculator', 'Hard', 40, 120, 149),
  ('maximum-profit-in-job-scheduling', 'Maximum Profit in Job Scheduling', 'Hard', 45, 135, 150),
  ('merge-k-sorted-lists', 'Merge k Sorted Lists', 'Hard', 30, 90, 151),
  ('largest-rectangle-in-histogram', 'Largest Rectangle in Histogram', 'Hard', 35, 105, 152),
  ('binary-tree-maximum-path-sum', 'Binary Tree Maximum Path Sum', 'Hard', 35, 105, 153),
  ('maximum-frequency-stack', 'Maximum Frequency Stack', 'Hard', 40, 120, 154),
  ('median-of-two-sorted-arrays', 'Median of Two Sorted Arrays', 'Hard', 40, 120, 155),
  ('longest-increasing-path-in-a-matrix', 'Longest Increasing Path in a Matrix', 'Hard', 40, 120, 156),
  ('longest-valid-parentheses', 'Longest Valid Parentheses', 'Hard', 35, 105, 157),
  ('design-in-memory-file-system', 'Design In-Memory File System', 'Hard', 40, 120, 158),
  ('employee-free-time', 'Employee Free Time', 'Hard', 35, 105, 159),
  ('word-search-ii', 'Word Search II', 'Hard', 40, 120, 160),
  ('alien-dictionary', 'Alien Dictionary', 'Hard', 45, 135, 161),
  ('bus-routes', 'Bus Routes', 'Hard', 45, 135, 162),
  ('sliding-window-maximum', 'Sliding Window Maximum', 'Hard', 35, 105, 163),
  ('palindrome-pairs', 'Palindrome Pairs', 'Hard', 40, 120, 164),
  ('reverse-nodes-in-k-group', 'Reverse Nodes in k-Group', 'Hard', 35, 105, 165),
  ('sudoku-solver', 'Sudoku Solver', 'Hard', 40, 120, 166),
  ('first-missing-positive', 'First Missing Positive', 'Hard', 35, 105, 167),
  ('n-queens', 'N-Queens', 'Hard', 40, 120, 168)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  difficulty = EXCLUDED.difficulty,
  minutes = EXCLUDED.minutes,
  points = EXCLUDED.points,
  order_index = EXCLUDED.order_index;
